version: '3.8'
services:
  flag_ssh_key_auth:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: flag_ssh_key_auth
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - PASSWORD_ACCESS=false
      - USER_NAME=student
      - PUBLIC_KEY_FILE=/config/keys/id_ed25519.pub
    volumes:
      - ./id_ed25519.pub:/config/keys/id_ed25519.pub:ro
      - ./flag.txt:/opt/flag.txt:ro
      - ./hint.txt:/opt/hint.txt:ro
