version: '3.8'
services:
  flag_web_basic_auth:
    image: nginx:alpine
    container_name: flag_web_basic_auth
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./htpasswd:/etc/nginx/htpasswd:ro
      - ./html:/usr/share/nginx/html:ro
