services:
  generator:
    platform: linux/amd64
    build: .
    volumes:
      - ${INPUTS_DIR}:/inputs:ro
      - ${OUTPUTS_DIR}:/outputs
    environment:
      - OUT_DIR=/outputs
      - CONFIG_PATH=/inputs/config.json
